spring:
  profiles:
    active: dev

---
server:
  port: 8201
spring:
  application:
    name: spring-boot-cloud-client
  profiles: dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka
---
server:
  port: 8202
spring:
  application:
    name: spring-boot-cloud-client
  profiles: test

eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka