spring:
  profiles:
    active: dev

---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: spring-boot-cloud-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_01?characterEncoding=utf-8
    username: root
    password: 123456789
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: spring-boot-cloud-provider:8001
    #    在eureka服务中可以在左下角显示的访问ip地址
    prefer-ip-address: true
info:
  app.name: spring-boot-cloud-provider
  company.name: http://www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: spring-boot-cloud-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_01?characterEncoding=utf-8
    username: root
    password: 123456789
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: spring-boot-cloud-provider:8001
    #    在eureka服务中可以在左下角显示的访问ip地址
    prefer-ip-address: true
info:
  app.name: spring-boot-cloud-provider
  company.name: http://www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$